mp_help:
	@echo mp_help: explicación de los argumentos necesario para ejecutar el programa
	@echo
	@echo Para poder ejecutar correctamente el programa, hay que pasarle un archivo como argumento.
	@echo Como el programa esta escrito en python utilizaremos el intérprete \"python3\".
	@echo El programa principal es \"mainMP.py\", así que una correcta llamada al programa sería:
	@echo
	@echo -e '\t' \"python3 mainMP.py nombre_archivo.extension\"
	@echo
	@echo La extension del archivo a leer que hemos elegido es \".in\" pero podría ser cualquier
	@echo otra como \".txt\"
	@echo
	@echo Con \"make mp_exec\" pueden ver un ejemplo de ejecucción.

mp_exec:
	@echo un ejemplo de ejecución:
	python3 mainMP.py McCulloch_Pitts.in
